Manifest zeus: Update  and add connagtive-qt5demo-image for sdk build
phytec/meta-esec-iotdm pull request #52
Opened 2021-07-16 08:30 UTC by motto-phytec

2021-07-19 14:32 UTC, mschwan-phytec requested changes

2021-07-19 14:32 UTC, mschwan-phytec commented on zeus.xml
> +  <project name="meta-imx" path="sources/meta-imx" remote="codeaurora" revision="refs/tags/rel_imx_5.4.70_2.3.0" upstream="zeus-5.4.70-2.3.0">
Please undo this change. We are going to use version 2.3.2 for the next release.

2021-07-19 14:32 UTC, mschwan-phytec commented on recipes-images/images/phytec-connagtive-qt5demo-image.bb
> +require recipes-images/images/phytec-connactive-start-image.bb
There is a typo here: "connagtive" with "g" not "c".

2021-07-20 06:42 UTC, motto-phytec commented on zeus.xml
> +  <project name="meta-imx" path="sources/meta-imx" remote="codeaurora" revision="refs/tags/rel_imx_5.4.70_2.3.0" upstream="zeus-5.4.70-2.3.0">
i know. this commit change the version from 2.3.2 to 2.3.0. it was wrong before.

2021-07-20 06:43 UTC, motto-phytec commented on recipes-images/images/phytec-connagtive-qt5demo-image.bb
> +require recipes-images/images/phytec-connactive-start-image.bb
is changed

2022-02-04 09:10 UTC, closed without merging