Migration distro and image from zeus to hardknott
phytec/meta-esec-iotdm pull request #76
Opened 2022-09-23 08:07 UTC by motto-phytec

an update from zeu to hardknott is not possible directly, because the following has changed
1. RAUC Bundle signing type has changed from plain (zeus) to the new type variety (hardknott)
2. RAUC certificate structure from selfsigned rauc ca to phytec main ca with rauc intermediate
3. The shadow_command has changed from hardcoded in awsclient version 1.3 (zeus) to configurable in aws/config.json by the awsclient 1.5 (hardknott)

2022-10-06 12:01 UTC, mschwan-phytec requested changes

2022-10-06 12:01 UTC, mschwan-phytec commented on conf/distro/ampliphy-vendor-connagtive-migration.conf
> +RAUC_CERT_FILE ?= "${CERT_PATH}/rauc/development-1.cert.pem"
These RAUC variables should be set in the migration bundle recipe, not the distro.

2022-10-06 12:01 UTC, mschwan-phytec commented on conf/distro/ampliphy-vendor-connagtive.conf
> +PREFERRED_VERSION_phytec-dev-ca = "1.2"
Setting the preferred version of phytec-dev-ca to 1.2 in the normal connagtive distro seems wrong. We only need it in the migration distro, right?

2022-10-06 12:01 UTC, mschwan-phytec commented on conf/distro/common-secure-connagtive.inc
> +
Remove this empty line.

2022-10-11 11:56 UTC, motto-phytec commented on conf/distro/ampliphy-vendor-connagtive.conf
> +PREFERRED_VERSION_phytec-dev-ca = "1.2"
the main certificate and rauc intermediate certificate are equal in version 1.2 and 1.3. The phytec-dev-ca is inthe ../build folder. So different builds with the same source use the same phytec-dev-ca folder.  This is the main reason for the same phytec-dev-ca version in all distros.

2022-10-11 13:17 UTC, motto-phytec commented on conf/distro/ampliphy-vendor-connagtive-migration.conf
> +RAUC_CERT_FILE ?= "${CERT_PATH}/rauc/development-1.cert.pem"
is moved to the migration bundle and migration distro is removed

2022-10-11 13:18 UTC, motto-phytec commented on conf/distro/common-secure-connagtive.inc
> +
is removed

2022-10-17 06:45 UTC, mschwan-phytec requested changes
What do you think about the bundle and image names? Maybe we should add "zeus-to-hardknott" to their names to make the affected versions clear. Although that makes them look quite bulky, it assures we don't run into name clashes for any possible future migrations.

2022-10-17 06:45 UTC, mschwan-phytec commented on conf/distro/ampliphy-vendor-connagtive.conf
> +PREFERRED_VERSION_phytec-dev-ca = "1.2"
But then, for all connagtive related distros to use the same phytec-dev-ca version in this layer, shouldn't we move that setting to the `common-secure-connagtive.inc`?

2022-10-17 08:08 UTC, motto-phytec commented on conf/distro/ampliphy-vendor-connagtive.conf
> +PREFERRED_VERSION_phytec-dev-ca = "1.2"
yes this is right. I move this to the common-secure-connagtive.inc.

2022-10-17 08:39 UTC, motto-phytec commented
I change the names for the migration image and bundle and add zeus-to-hardknott in the receipes names.

2022-10-17 08:43 UTC, mschwan-phytec approved these changes

2022-10-17 08:44 UTC, merged